### ISSUE TITLE
Poor interaction with NullableArrays

### ISSUE THREAD

**Issue by nalimilan** [davidavdav/NamedArrays.jl#25]
`NamedArray`s don't work well with `NullableArray` currently. First, the type information isn't correct:
```julia
julia> NamedArray(NullableArray([1]))
1-element NamedArray{Nullable{Int64},1}:
...
```

I suggest printing `NamedArray{NullableArray{Int64,1}}:` or `NullableArray{Int64,1} with names:`. This pattern could be used for all array types.

Second, the printing is quite verbose, as `Nullable{T}` is repeated for each element. I think this should be fixed in Julia Base: https://github.com/JuliaLang/julia/pull/15928.

**Comment by nalimilan** [comment]
The second issue is fixed now with NullableArrays from git master, but the first one remains.

**Comment by davidavdav** [comment]
I am sorry, I don't understand what you mean.  
```
julia> NullableArray
ERROR: UndefVarError: NullableArray not defined
```

**Comment by nalimilan** [comment]
You need `using NullableArrays`.

**Comment by davidavdav** [comment]
OK.  But I still don't understand your request.  It looks like `NamedArray(NullableArray([1]))` gives straight out of the box what you would want: an Array of `Nullable{Int}` with names.  It is not an Array of `NullableArray{Int}` with names, the `eltype()` is `Nullable{Int}`, I would think. 

I agree that printing is pretty verbose.  If there is a print statement of a Nullable that gives me ether `#NULL` (why the hash?) or the values, I would be glad to use that.

**Comment by nalimilan** [comment]
> OK. But I still don't understand your request. It looks like NamedArray(NullableArray([1])) gives straight out of the box what you would want: an Array of Nullable{Int} with names. It is not an Array of NullableArray{Int} with names, the eltype() is Nullable{Int}, I would think.

It returns a `NamedArray` wrapping a `NullableArray{Int}`, not wrapping an `Array{Int}`:
```julia
julia> typeof(NamedArray(NullableArray([1])))
NamedArrays.NamedArray{Nullable{Int64},1,NullableArrays.NullableArray{Int64,1},Tuple{Dict{String,Int64}}}
```

That's not a big deal, but I think it would be better to always print the actual array type. For example, there's the same problem with sparse vectors/matrices (`NamedArray(sparse([1]))`).

> I agree that printing is pretty verbose. If there is a print statement of a Nullable that gives me ether #NULL (why the hash?) or the values, I would be glad to use that.

As I said, the printing looks OK now with the latest version of NullableArrays.

**Comment by davidavdav** [comment]
I am sorry, I fail to get the point.  

If you want to have a `NamedArray` wrapping an `Array{Nullable{Int}}` call `NamedArray(Array{Nullable{Int}})`.  

Or is your problem that the storage container layout is not show in printing the `NamedArray`, only the element type?  This is due to https://github.com/davidavdav/NamedArrays.jl/issues/18.

**Comment by nalimilan** [comment]
> Or is your problem that the storage container layout is not show in printing the NamedArray, only the element type? This is due to #18.

Yes, that's what I meant. The current printing is good for standard `Array`, but not so much for other types. I know that was my suggestion, but I now think we should find something else.

**Comment by davidavdav** [comment]
I had a look at SparseMatrix, but this seems to be more limited than NamedArray, as `ndims == 2`.  But I can have a look if for that case I can make an exception.

**Comment by nalimilan** [comment]
Rather than an exception, I think we should find a general solution which would always show the wrapped array type. That's why I proposed `Array{Int64,1} with names`, `NullableArray{Int64,1} with names`, etc.

**Comment by davidavdav** [comment]
The array type itself is one thing, but the way the array is printed is very dependent on the array type. 

It is difficult to maintain support for all possible other array types.  There is a lot of code duplication, which isn't great.  It would be better if there were hooks in Base for things like
- printing the row/column/... number/name
- printing an array value
- finding out various widths

The implementations for showing Array, SparseMatrixCSC, NullableArray, NamedArray are all quite different.  I now have a special case for SparseMatrixCSC, which is basically copied code from sparsematrix.jl minus the code referencing stuff that I can't find---and this code is quite different from my own code.  I would rather have the two pieces of code integrated.   But that is a discussion that should be taken to Julia Base.

**Comment by nalimilan** [comment]
Yes, that would be very useful, but I think that's quite orthogonal to the present bug. Here I'm only talking about the summary line, which should be much easier to fix.

**Comment by nalimilan** [comment]
Ah, hadn't noticed you pushed a fix. Let's close this then, thanks! The larger printing issues should be discussed in Base, though you may want to wait until 0.5 is released as people may not have the time for this right now.
